# Generated by Django 4.1.7 on 2023-04-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_tag_options_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('locality',), 'verbose_name_plural': 'Addresses'},
        ),
    ]
