# Generated by Django 4.1.7 on 2023-04-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_address_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
