# Generated by Django 4.2.1 on 2023-05-15 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0015_customuser_alter_usertag_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertag',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='usertag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
